---
- name: prepare for deploy...
  hosts: prod_server
  user: admin
  vars:
    dest: ''
    colon: ':'
    env:
      RAILS_ENV: production
      PATH: ''

  tasks:
    - name: git clone/pull
      git:
        repo={{repo}}
        dest={{dest}}
        accept_hostkey=yes 
        force=yes 

    - name: bundle install
      command:
        bundle install --jobs=4 --path=vendor/bundler --binstubs=vendor/bin --without test development
        chdir={{ dest }}
      environment: env

    - name: test bin/unicorn
      command:
        test -f bin/unicorn
        chdir={{ dest }}
      register: test_bin_unicorn
      ignore_errors: yes

    - name: copy bin/unicorn
      command:
        cp bin/unicorn.sample bin/unicorn
        chdir={{ dest }}
      when: test_bin_unicorn|failed

    - name: edit bin/unicorn
      lineinfile:
        dest={{ dest }}/bin/unicorn
        regexp='^APP_ROOT=\/path\/to\/{{ project }}$'
        line='APP_ROOT={{ dest }}'
      when: test_bin_unicorn|failed
